version: 2.1
jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -backend-config=/tmp/project/env/sqa.tfbackend 
            terraform plan -backend-config=/tmp/project/env/sqa.tfbackend -var-file=/tmp/project/env/sqa.tfvars -out tfapply  
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply 
      - persist_to_workspace:
          root: .
          paths:
            - .            
  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -backend-config=/tmp/project/env/sqa.tfbackend -var-file=-var-file=/tmp/project/env/sqa.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  build-artifact:
    jobs: 
      - plan-apply
      - apply:
          requires:
            - plan-apply
      - plan-destroy:
          requires:
            - apply              
